package com.atoz.akkaratanapat.daogenerator;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.atoz.akkaratanapat.daogenerator.Pharmacy;

import com.atoz.akkaratanapat.daogenerator.PharmacyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pharmacyDaoConfig;

    private final PharmacyDao pharmacyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pharmacyDaoConfig = daoConfigMap.get(PharmacyDao.class).clone();
        pharmacyDaoConfig.initIdentityScope(type);

        pharmacyDao = new PharmacyDao(pharmacyDaoConfig, this);

        registerDao(Pharmacy.class, pharmacyDao);
    }
    
    public void clear() {
        pharmacyDaoConfig.clearIdentityScope();
    }

    public PharmacyDao getPharmacyDao() {
        return pharmacyDao;
    }

}
