package com.atoz.akkaratanapat.daogenerator;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PHARMACY".
 */
@Entity
public class Pharmacy {

    @Id(autoincrement = true)
    private Long id;
    private String name;
    private String address;
    private String province;
    private String district;
    private Double lat;
    private Double lng;
    private String number;
    private String owner;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Pharmacy() {
    }

    public Pharmacy(Long id) {
        this.id = id;
    }

    @Generated
    public Pharmacy(Long id, String name, String address, String province, String district, Double lat, Double lng, String number, String owner) {
        this.id = id;
        this.name = name;
        this.address = address;
        this.province = province;
        this.district = district;
        this.lat = lat;
        this.lng = lng;
        this.number = number;
        this.owner = owner;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getDistrict() {
        return district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLng() {
        return lng;
    }

    public void setLng(Double lng) {
        this.lng = lng;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
